name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build plugin
        run: npm run build

      - name: Create plugin zip
        run: |
          mkdir -p dist
          zip -r dist/nali-custom-block.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x "dist/*" \
            -x ".github/*" \
            -x "*.zip"

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: nali-custom-block
          path: dist/nali-custom-block.zip
